---
profile_foreman_proxy::foreman_host: foreman.foreman.vagrant
profile_puppet::puppetmaster: puppet.foreman.vagrant
profile_puppet::server_foreman_url: "http://foreman.foreman.vagrant"
profile_puppet::server_puppetdb_host: puppetdb.foreman.vagrant