---
profile_firewall::ensure: stopped
profile_puppetagent::ca_server: puppet.foreman.vagrant
profile_puppetmaster::ca_server: puppet.foreman.vagrant
profile_puppetmaster::puppetmaster: puppet.foreman.vagrant